version: '2'
services:

  haproxy:
    image: eeacms/haproxy
    depends_on:
    - wordpress
    ports:
    - "80:5000"
    - "1936:1936"
    environment:
      BACKENDS: "wordpress"
      DNS_ENABLED: "true"  

  wordpress:
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    volumes:
      - ./wp-app:/var/www/html # Full wordpress project
    environment:
      WORDPRESS_DB_HOST: db 
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: user_db
      WORDPRESS_DB_PASSWORD: user_db_password
    depends_on:
      - db  
             
  db:
    image: mysql:latest # https://hub.docker.com/_/mysql/
    ports:
      - 3306:3306
    restart: always
    environment:      
      MYSQL_DATABASE: wordpress_db
      MYSQL_ROOT_PASSWORD: password_db
      MYSQL_USER: user_db
      MYSQL_PASSWORD: user_db_password      

